import type { Cache } from '../types/cache.js'
import type { CacheInvalidateEvent } from '../types/events.js'

/**
 * Creates an SSE (Server-Sent Events) handler for real-time cache invalidation.
 * This is used in long-running server mode to push invalidation events to clients.
 */
export function createSSEHandler(cache: Cache) {
  return async function sseLoader({ request }: { request: Request }) {
    const stream = new ReadableStream({
      start(controller) {
        const encoder = new TextEncoder()

        // Handler for invalidation events
        const handler = (event: CacheInvalidateEvent) => {
          // Format SSE message
          const message = `event: invalidate\ndata: ${JSON.stringify(event)}\n\n`
          controller.enqueue(encoder.encode(message))
        }

        // Subscribe to invalidation events
        cache.on('invalidate', handler)

        // Clean up when connection closes
        request.signal.addEventListener('abort', () => {
          cache.off('invalidate', handler)
          try {
            controller.close()
          } catch (e) {
            // Controller may already be closed
          }
        })
      },
    })

    // Return SSE response
    return new Response(stream, {
      headers: {
        'Content-Type': 'text/event-stream',
        'Cache-Control': 'no-cache',
        Connection: 'keep-alive',
      },
    })
  }
}

/**
 * Generate an SSE resource route file content
 */
export function generateSSERoute(): string {
  return `
// Auto-generated by remix-cache
// app/routes/api.cache-events.tsx

import { createSSEHandler } from 'remix-cache/server'
import { cache } from '~/cache.server'

export const loader = createSSEHandler(cache)
`.trim()
}
